root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/bot main.go"
bin = "tmp/bot"
delay = 1000
watch = true

[log]
timestamp = false

[watch]
include = ["."]
exclude = ["tmp", ".git", "vendor"]
